services:
  api:
    build:
      context: container/api
      dockerfile: Dockerfile
    ports:
      - 20000:3000
    environment:
      - TZ=Asia/Seoul
      - LANG=C.UTF-8
    restart: always
    volumes:
      - dependency_data:/app/dependency_data
    depends_on:
      - db
      - redis
  
  client:
    build:
      context: container/client
      dockerfile: Dockerfile
    ports:
      - 20001:3000
    environment:
      - TZ=Asia/Seoul
      - LANG=C.UTF-8
    restart: always
    volumes:
      - dependency_data:/app/dependency_data
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Seoul
      - PGTZ=Asia/Seoul
      - LANG=C.UTF-8
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bwasp
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    environment:
      - TZ=Asia/Seoul
      - LANG=C.UTF-8
    restart: always
    volumes:
      - ./db/redis_data:/data

  processor:
    build:
      context: container/processor
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Seoul
      - LANG=C.UTF-8
    depends_on:
      - db
      - redis
    volumes:
      - dependency_data:/app/dependency_data

volumes:
  postgres_data:
  redis_data:
  dependency_data:

networks: