FROM redis:alpine

ENV TZ=Asia/Seoul
ENV LANG=C.UTF-8

RUN apk add --no-cache tzdata

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 6379

# CMD ["redis-server"]