"""empty message

Revision ID: c7270f7bdde7
Revises: 
Create Date: 2021-11-24 10:52:12.414422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7270f7bdde7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CSPEvaluator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('related_Packet', sa.Integer(), nullable=False),
    sa.Column('URL', sa.TEXT(), nullable=False),
    sa.Column('URI', sa.TEXT(), nullable=False),
    sa.Column('action_URL', sa.TEXT(), nullable=False),
    sa.Column('action_URL_Type', sa.TEXT(), nullable=False),
    sa.Column('params', sa.TEXT(), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=False),
    sa.Column('attackVector', sa.TEXT(), nullable=False),
    sa.Column('impactRate', sa.Integer(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('Details', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('targetURL', sa.TEXT(), nullable=False),
    sa.Column('knownInfo', sa.TEXT(), nullable=False),
    sa.Column('recursiveLevel', sa.TEXT(), nullable=False),
    sa.Column('uriPath', sa.TEXT(), nullable=False),
    sa.Column('done', sa.BOOLEAN(), nullable=True),
    sa.Column('maximumProcess', sa.TEXT(), nullable=0),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('statusCode', sa.Integer(), nullable=False),
    sa.Column('requestType', sa.TEXT(), nullable=False),
    sa.Column('requestJson', sa.TEXT(), nullable=False),
    sa.Column('responseHeader', sa.TEXT(), nullable=False),
    sa.Column('responseBody', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service', sa.TEXT(), nullable=False),
    sa.Column('target', sa.TEXT(), nullable=False),
    sa.Column('port', sa.TEXT(), nullable=False),
    sa.Column('result', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('systeminfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('data', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('systeminfo')
    op.drop_table('ports')
    op.drop_table('packets')
    op.drop_table('job')
    op.drop_table('domain')
    op.drop_table('CSPEvaluator')
    # ### end Alembic commands ###
